trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: "ubuntu-18.04"
        python.version: "3.6"
      Python37Windows:
        imageName: "vs2017-win2016"
        python.version: "3.7"
      Python38Mac:
        imageName: "macos-10.14"
        python.version: "3.8"
      Python39Linux:
        imageName: "ubuntu-18.04"
        python.version: "3.9"
      Python39Windows:
        imageName: "vs2017-win2016"
        python.version: "3.9"
      Python39Mac:
        imageName: "macos-10.14"
        python.version: "3.9"
      Python310Linux:
        imageName: "ubuntu-20.04"
        python.version: "3.10"
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - script: |
      python -m pip freeze > installed.txt
      python -m pip uninstall -y -r installed.txt
    displayName: "Uninstall all packages"

  - bash: |
      SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
      python -m pip install dist/$SDIST
    displayName: 'Install from sdist'

  - script: |
      python -m pip install wheel
      python -m pip install -r requirements.txt
      python -m pip install fasttext
      python -m pytest --pyargs floret
    displayName: 'Run tests'

  - script: |
      python tests/runtests.py -u
    displayName: 'Run upstream unit tests'
